# Generated by Django 5.1.7 on 2025-04-03 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[("A", "Type A"), ("B", "Type B"), ("C", "Type C")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_added", models.IntegerField(default=0)),
                ("quantity_removed", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("remaining_stock", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.item"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="stock_stock_period__e83de4_idx",
                    )
                ],
            },
        ),
    ]
